version: '3.8'

services:
  postgres:
    image: postgres
    env_file:
      - ./.dev/envs/postgres.env
    volumes:
      - /home/mclement/projects/emy-room-booking-frontend/.dev/db:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  back:
    image: emy_backend
    env_file:
      - ./.dev/envs/back.env
    ports:
      - "3002:3000"
  # front:
  #   image: emy_frontend
  #   env_file:
  #     - ./.dev/envs/front.env
  #   ports:
  #     - "3001:3000"
